SELECT
    Child.ITEM_ID,
    Child.ITEM_NAME,
    Child.RARITY
FROM
    ITEM_INFO Child
    JOIN ITEM_TREE T ON Child.ITEM_ID = T.ITEM_ID
    JOIN ITEM_INFO Parent ON T.PARENT_ITEM_ID = Parent.ITEM_ID
WHERE
    Parent.RARITY = "RARE"
ORDER BY
    Child.ITEM_ID DESC;